const STORAGE_KEY='nexsi_demo_v1_1';
const STATUTS=['pas encore','vu','fait avec aide','fait en autonomie','encadré un élève','maîtrisé'];
const DEFAULT={onboarded:false,tipDismissed:false,profile:{prenom:'',annee:'1',ifsi:''},connectors:{drive:{connected:false,lastSync:null},ent:{connected:false,lastSync:null,ifsiName:''}},settings:{suggestions:true,stageOnTop:false,notifications:false},priorities:[{id:1,title:'Réviser UE 2.11 — Pharmacologie',meta:'Évaluation écrite · 29 juil.',type:'eval',urgent:true},{id:2,title:'Préparer le stage de chirurgie',meta:'Début le 4 août · CHU',type:'stage'},{id:3,title:'Remplir le journal de bord J3',meta:'À rendre avant dimanche',type:'task'}],tasks:[{id:1,text:'Importer mon emploi du temps',done:false,ue:null},{id:2,text:'Lire le protocole de transfusion',done:false,ue:'UE 4.4'},{id:3,text:'Appeler le cadre de santé',done:true,ue:null}],evaluations:[{id:1,titre:'UE 2.11 Pharmacologie',date:'2026-07-29',modalite:'écrit'},{id:2,titre:'UE 3.1 Raisonnement clinique',date:'2026-08-12',modalite:'oral'},{id:3,titre:'APP stage chirurgie',date:'2026-08-20',modalite:'à rendre'}],travaux:{perso:[{id:1,titre:'Fiche UE 2.11',type:'pdf',date:'2026-07-20'},{id:2,titre:'Notes anatomie',type:'note',date:'2026-07-18'}],groupe:[{id:1,titre:'TD groupe B — Cas clinique',type:'drive',date:'2026-07-15'}],biblio:[{id:1,titre:'réussir-ton-ifsi.fr',type:'externe'},{id:2,titre:'fiche-ide.com',type:'externe'}]},stage:{actif:false,lieu:'',debut:'',fin:'',progression:0,objectifs:[],journal:[]},soins:[{id:'hygiene-mains',nom:'Hygiène des mains (SHA)',categorie:'Hygiène',statut:'maîtrisé'},{id:'pansement-simple',nom:'Pansement simple',categorie:'Pansements',statut:'fait en autonomie'},{id:'injection-sc',nom:'Injection sous-cutanée',categorie:'Injections',statut:'fait avec aide'},{id:'injection-im',nom:'Injection intramusculaire',categorie:'Injections',statut:'vu'},{id:'perfusion',nom:'Pose de perfusion',categorie:'Voies veineuses',statut:'pas encore'},{id:'prise-sang',nom:'Prélèvement veineux',categorie:'Prélèvements',statut:'vu'},{id:'sondage-vesical',nom:'Sondage vésical',categorie:'Sondages',statut:'pas encore'},{id:'transfusion',nom:'Transfusion sanguine',categorie:'Transfusion',statut:'pas encore'},{id:'glycemie',nom:'Glycémie capillaire',categorie:'Surveillance',statut:'maîtrisé'},{id:'constantes',nom:'Prise de constantes',categorie:'Surveillance',statut:'maîtrisé'},{id:'aerosol',nom:'Aérosolthérapie',categorie:'Respiratoire',statut:'fait en autonomie'},{id:'oxygene',nom:'Oxygénothérapie',categorie:'Respiratoire',statut:'vu'}],journalEntries:[],checklistFournitures:[{id:1,text:'Blouse / tenue professionnelle',done:false},{id:2,text:'Chaussures fermées antidérapantes',done:false},{id:3,text:'Badge étudiant',done:false},{id:4,text:'Carnet de stage / portfolio',done:false},{id:5,text:'Stylo 4 couleurs + feutre noir',done:false},{id:6,text:'Montre avec trotteuse',done:false},{id:7,text:'Ciseaux + pince (si demandé)',done:false},{id:8,text:'Carnet de notes de poche',done:false}]};
let state=loadState(),currentTab='accueil',deferredInstallPrompt=null;
function loadState(){try{const r=localStorage.getItem(STORAGE_KEY);if(r){const p=JSON.parse(r);return Object.assign(JSON.parse(JSON.stringify(DEFAULT)),p,{profile:Object.assign({},DEFAULT.profile,p.profile||{}),connectors:Object.assign({},DEFAULT.connectors,p.connectors||{}),settings:Object.assign({},DEFAULT.settings,p.settings||{})});}}catch(e){}return JSON.parse(JSON.stringify(DEFAULT));}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
function showToast(m,d=2500){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),d);}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function fmt(iso){if(!iso)return'';return new Date(iso+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'});}
function greeting(){const h=new Date().getHours();return h<12?'Bonjour':h<18?'Bon après-midi':'Bonsoir';}
function todayLabel(){return new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'});}
function initials(n){return(n||'E').charAt(0).toUpperCase();}
function renderOnboarding(){const el=document.getElementById('onboarding');if(state.onboarded){el.classList.add('hidden');return;}el.classList.remove('hidden');el.innerHTML=`<div class="onboarding-logo">NEXSI</div><p class="onboarding-tagline">L'app qui t'aide à t'organiser pendant tes 3 ans d'IFSI.<br>Tes données restent sous ton contrôle.</p><div class="onboarding-step" id="ob-step1"><h2>Salut 👋 Comment tu t'appelles ?</h2><input type="text" id="ob-prenom" placeholder="Ton prénom" maxlength="30"><button class="btn btn-primary" onclick="obNext(1)">Continuer</button></div><div class="onboarding-step hidden" id="ob-step2"><h2>Tu es en quelle année ?</h2><select id="ob-annee"><option value="1">1re année</option><option value="2">2e année</option><option value="3">3e année</option></select><input type="text" id="ob-ifsi" placeholder="Ton IFSI (optionnel)" maxlength="60"><button class="btn btn-primary" onclick="obNext(2)">C'est parti</button><button class="btn btn-ghost btn-block mt-1" onclick="obSkip()">Passer</button></div><div class="onboarding-footer">Demo · Données locales uniquement</div>`;}
function obNext(step){if(step===1){const p=document.getElementById('ob-prenom').value.trim();if(!p){showToast('Dis-moi ton prénom');return;}state.profile.prenom=p;document.getElementById('ob-step1').classList.add('hidden');document.getElementById('ob-step2').classList.remove('hidden');}else{state.profile.annee=document.getElementById('ob-annee').value;state.profile.ifsi=document.getElementById('ob-ifsi').value.trim();finishOnboarding();}}
function obSkip(){state.profile.prenom=state.profile.prenom||'Étudiant(e)';finishOnboarding();}
function finishOnboarding(){state.onboarded=true;saveState();document.getElementById('onboarding').classList.add('hidden');renderAll();showToast('Bienvenue '+state.profile.prenom+' !');}
function switchTab(tab){currentTab=tab;document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));document.getElementById('panel-'+tab)?.classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));document.querySelector('.nav-item[data-tab="'+tab+'"]')?.classList.add('active');document.getElementById('header-title').textContent={accueil:'Accueil',fiches:'Fiches',terrain:'Terrain',soins:'Soins'}[tab]||'NEXSI';closeAI();closeSearch();closeScreen();}
function renderAll(){renderAccueil();renderFiches('perso');renderTerrain();renderSoins();}
function renderAccueil(){const prenom=state.profile.prenom||'toi';const pri=state.priorities.slice(0,3);const tip=!state.tipDismissed?`<div class="tip-card"><div class="tip-icon">💡</div><div class="tip-body"><div class="tip-title">Astuce</div><div class="tip-text">Connecte Google Drive pour protéger ton journal.</div></div><button class="tip-close" onclick="dismissTip()">✕</button></div>`:'';document.getElementById('panel-accueil').innerHTML=`<div class="greeting"><h2>${greeting()} ${esc(prenom)} 👋</h2><p>${todayLabel()}</p></div>${tip}<div class="quick-actions"><button class="quick-action" onclick="openSearch()"><div class="qa-icon">🔍</div><div class="qa-label">Rechercher</div></button><button class="quick-action" onclick="openAI()"><div class="qa-icon">✨</div><div class="qa-label">Assistant IA</div></button><button class="quick-action" onclick="openConnectors()"><div class="qa-icon">🔗</div><div class="qa-label">Connecteurs</div></button><button class="quick-action" onclick="openSettings()"><div class="qa-icon">⚙️</div><div class="qa-label">Réglages</div></button></div><div class="section"><div class="section-title"><span>Priorités du jour</span><span class="badge">${pri.length}/3</span></div>${pri.map(p=>`<div class="card priority-card ${p.urgent?'urgent':''} ${p.type==='stage'?'stage':''}"><div class="card-title">${esc(p.title)}</div><div class="card-meta">${p.urgent?'<span class="badge danger">Urgent</span>':''}<span>${esc(p.meta)}</span></div><button class="card-cta" onclick="handlePriority(${p.id})">Voir →</button></div>`).join('')}</div><div class="section"><div class="section-title">Évaluations</div>${state.evaluations.map(e=>`<div class="card"><div class="card-title">${esc(e.titre)}</div><div class="card-meta"><span class="badge">${e.modalite}</span><span>${fmt(e.date)}</span></div></div>`).join('')}</div><div class="section"><div class="section-title"><span>Tâches</span><button class="btn btn-sm btn-secondary" onclick="openAddTask()">+ Ajouter</button></div><div class="card" style="padding:.5rem 1rem">${state.tasks.map(t=>`<div class="list-item" style="padding:.6rem 0" onclick="toggleTask(${t.id})"><span style="font-size:1.2rem">${t.done?'✅':'⬜'}</span><div class="item-content"><div class="item-title" style="${t.done?'text-decoration:line-through;opacity:.6':''}">${esc(t.text)}</div>${t.ue?`<div class="item-sub">${t.ue}</div>`:''}</div></div>`).join('')}</div></div>`;}
function dismissTip(){state.tipDismissed=true;saveState();renderAccueil();}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(t){t.done=!t.done;saveState();renderAccueil();showToast(t.done?'Terminé ✓':'Réouverte');}}
function handlePriority(id){const p=state.priorities.find(x=>x.id===id);if(p&&p.type==='stage')switchTab('terrain');else if(p)showToast(p.title);}
function openAddTask(){openModal('Nouvelle tâche',`<div class="form-group"><label>Description</label><input type="text" id="new-task-text" maxlength="120"></div><div class="form-group"><label>UE</label><input type="text" id="new-task-ue" maxlength="20"></div><button class="btn btn-primary btn-block" onclick="saveNewTask()">Ajouter</button>`);}
function saveNewTask(){const text=document.getElementById('new-task-text').value.trim();if(!text){showToast('Écris une description');return;}state.tasks.unshift({id:Date.now(),text,done:false,ue:document.getElementById('new-task-ue').value.trim()||null});saveState();closeModal();renderAccueil();showToast('Ajoutée');}
/* See full source in repo history for remaining functions: Fiches, Terrain, Soins, Connectors, Settings, Search, AI, Calc */
function renderFiches(sub='perso'){const data=state.travaux[sub]||[];const labels={perso:'Travaux personnels',groupe:'Travaux en groupe',biblio:'Bibliothèque'};const icons={perso:'📄',groupe:'👥',biblio:'📚',pdf:'📕',note:'📝',drive:'📂',externe:'🔗'};document.getElementById('panel-fiches').innerHTML=`<div class="sub-tabs"><button class="sub-tab ${sub==='perso'?'active':''}" onclick="renderFiches('perso')">Perso</button><button class="sub-tab ${sub==='groupe'?'active':''}" onclick="renderFiches('groupe')">Groupe</button><button class="sub-tab ${sub==='biblio'?'active':''}" onclick="renderFiches('biblio')">Bibliothèque</button></div><div class="section"><div class="section-title"><span>${labels[sub]}</span><button class="btn btn-sm btn-secondary" onclick="openAddTravail('${sub}')">+ Ajouter</button></div>${data.length?`<div class="card" style="padding:.25rem 1rem">${data.map(d=>`<div class="list-item" onclick="showToast('Demo')"><div class="item-icon">${icons[d.type]||'📄'}</div><div class="item-content"><div class="item-title">${esc(d.titre)}</div></div></div>`).join('')}</div>`:`<div class="empty-state"><p>Aucun document</p><button class="btn btn-primary btn-sm" onclick="openAddTravail('${sub}')">Ajouter</button></div>`}</div>`;}
function openAddTravail(sub){openModal('Ajouter',`<div class="form-group"><label>Titre</label><input type="text" id="new-trav-titre" maxlength="100"></div><div class="form-group"><label>Type</label><select id="new-trav-type"><option value="note">Note</option><option value="pdf">PDF</option><option value="drive">Drive</option></select></div><button class="btn btn-primary btn-block" onclick="saveNewTravail('${sub}')">Ajouter</button>`);}
function saveNewTravail(sub){const titre=document.getElementById('new-trav-titre').value.trim();if(!titre){showToast('Titre requis');return;}if(!state.travaux[sub])state.travaux[sub]=[];state.travaux[sub].unshift({id:Date.now(),titre,type:document.getElementById('new-trav-type').value,date:new Date().toISOString().slice(0,10)});saveState();closeModal();renderFiches(sub);showToast('Ajouté');}
function renderTerrain(){const s=state.stage;const cd=state.checklistFournitures.filter(c=>c.done).length;document.getElementById('panel-terrain').innerHTML=`<div class="section"><div class="section-title">Mon stage</div>${s.actif?`<div class="card"><div class="card-title">${esc(s.lieu)}</div><div class="card-meta">${fmt(s.debut)} → ${fmt(s.fin)}</div><div class="progress-bar"><div class="fill" style="width:${s.progression}%"></div></div><button class="card-cta" onclick="openJournalDetail()">Journal →</button></div>`:`<div class="card"><div class="card-title">Pas encore de stage</div><button class="btn btn-primary btn-sm mt-2" onclick="openMockStage()">Simuler une affectation</button></div>`}</div><div class="section"><div class="section-title">Préparation</div><div class="card" style="padding:.4rem 1rem"><div class="list-item" style="border:none;padding:.55rem 0" onclick="openObjectifs()"><div class="item-icon">🎯</div><div class="item-content"><div class="item-title">Objectifs</div></div></div><div class="list-item" style="border:none;padding:.55rem 0" onclick="openChecklist()"><div class="item-icon">📋</div><div class="item-content"><div class="item-title">Fournitures (${cd}/${state.checklistFournitures.length})</div></div></div></div></div><div class="section"><div class="section-title">Journal</div><div class="card"><p class="text-sm text-muted mb-1">Anonymisé · Secret professionnel</p>${state.journalEntries.slice(-3).reverse().map(j=>`<div class="list-item"><div class="item-icon">📔</div><div class="item-content"><div class="item-title">${esc(j.titre)}</div><div class="item-sub">${fmt(j.date)}</div></div></div>`).join('')}<button class="btn btn-secondary btn-sm btn-block mt-1" onclick="openAddJournal()">+ Entrée</button></div></div>`;}
function openMockStage(){state.stage={actif:true,lieu:'CHU — Chirurgie orthopédique',debut:'2026-08-04',fin:'2026-09-12',progression:15,objectifs:['Préparation pré-op','Pansement chirurgical','Gestion douleur','Toilette complète','Transmission'].map((t,i)=>({id:i+1,text:t,done:false})),journal:[]};saveState();renderTerrain();showToast('Stage activé ✓');}
function openObjectifs(){if(!state.stage.objectifs?.length){state.stage.objectifs=[{id:1,text:'Organisation du service',done:false},{id:2,text:'Gestes de base',done:false}];saveState();}openScreen('Objectifs',`<div class="card" style="padding:.5rem 1rem">${state.stage.objectifs.map(o=>`<div class="checklist-item"><div class="check ${o.done?'done':''}" onclick="toggleObjectif(${o.id})">${o.done?'✓':''}</div><div class="check-label ${o.done?'done':''}">${esc(o.text)}</div></div>`).join('')}</div>`);}
function toggleObjectif(id){const o=state.stage.objectifs.find(x=>x.id===id);if(o){o.done=!o.done;saveState();openObjectifs();}}
function openChecklist(){openScreen('Fournitures',`<div class="card" style="padding:.5rem 1rem">${state.checklistFournitures.map(c=>`<div class="checklist-item"><div class="check ${c.done?'done':''}" onclick="toggleChecklist(${c.id})">${c.done?'✓':''}</div><div class="check-label ${c.done?'done':''}">${esc(c.text)}</div></div>`).join('')}</div>`);}
function toggleChecklist(id){const c=state.checklistFournitures.find(x=>x.id===id);if(c){c.done=!c.done;saveState();openChecklist();}}
function openAddJournal(){openModal('Journal',`<div class="form-group"><label>Titre</label><input type="text" id="new-j-titre" maxlength="80"></div><div class="form-group"><label>Notes</label><textarea id="new-j-notes"></textarea></div><button class="btn btn-primary btn-block" onclick="saveNewJournal()">Enregistrer</button>`);}
function saveNewJournal(){const titre=document.getElementById('new-j-titre').value.trim();if(!titre){showToast('Titre requis');return;}state.journalEntries.push({id:Date.now(),titre,notes:document.getElementById('new-j-notes').value.trim(),date:new Date().toISOString().slice(0,10)});saveState();closeModal();renderTerrain();showToast('Enregistré');}
function openJournalDetail(){openScreen('Journal',state.journalEntries.slice().reverse().map(j=>`<div class="card"><div class="card-title">${esc(j.titre)}</div><div class="card-meta">${fmt(j.date)}</div></div>`).join('')+'<button class="btn btn-primary btn-block mt-2" onclick="closeScreen();openAddJournal()">+ Entrée</button>');}
function renderSoins(filter=''){const q=filter.toLowerCase().trim();let list=state.soins;if(q)list=list.filter(s=>s.nom.toLowerCase().includes(q)||s.categorie.toLowerCase().includes(q));const cats={};list.forEach(s=>{if(!cats[s.categorie])cats[s.categorie]=[];cats[s.categorie].push(s);});document.getElementById('panel-soins').innerHTML=`<div class="warning-banner"><span>⚠️</span><span>Pédagogique — <strong>jamais pour le soin réel</strong>.</span></div><div class="search-bar"><span>🔍</span><input type="search" id="soins-search" placeholder="Rechercher…" value="${esc(filter)}" oninput="renderSoins(this.value)"></div><div class="section"><div class="section-title">Carnet de gestes</div>${Object.entries(cats).map(([cat,items])=>`<div style="margin-bottom:1rem"><div class="section-title">${esc(cat)}</div>${items.map(s=>`<div class="card"><div class="card-title">${esc(s.nom)}</div><div class="status-pills">${STATUTS.map(st=>`<button class="status-pill ${s.statut===st?'active':''}" onclick="setStatutGeste('${s.id}','${st}')">${st}</button>`).join('')}</div></div>`).join('')}</div>`).join('')}</div><div class="section"><div class="section-title">Calculateur</div><div class="card"><button class="btn btn-secondary btn-sm btn-block" onclick="openCalculateur()">Dose (entraînement)</button></div></div>`;}
function setStatutGeste(id,st){const s=state.soins.find(x=>x.id===id);if(s){s.statut=st;saveState();renderSoins(document.getElementById('soins-search')?.value||'');showToast(st);}}
function openCalculateur(){openScreen('Calculateur',`<div class="warning-banner"><span>⚠️</span><span>Fictif uniquement</span></div><div class="card"><div class="calc-grid"><div class="calc-field"><label>Dose (mg)</label><input type="number" id="calc-dose" value="500"></div><div class="calc-field"><label>Conc. (mg/ml)</label><input type="number" id="calc-conc" value="100"></div></div><button class="btn btn-primary btn-block mt-2" onclick="runCalc()">Calculer</button><div id="calc-out" class="calc-result" style="display:none"><div class="result-value" id="calc-vol">—</div></div></div>`);}
function runCalc(){const d=parseFloat(document.getElementById('calc-dose').value)||0,c=parseFloat(document.getElementById('calc-conc').value)||1;document.getElementById('calc-vol').textContent=(d/c).toFixed(2);document.getElementById('calc-out').style.display='block';}
function openConnectors(){const d=state.connectors.drive,e=state.connectors.ent;openScreen('Connecteurs',`<div class="connector-card"><div class="conn-icon drive">📁</div><div class="conn-body"><div class="conn-title">Google Drive</div><div class="conn-status"><span class="status-dot ${d.connected?'on':''}"></span>${d.connected?'Connecté':'Non connecté'}</div></div><button class="btn btn-sm ${d.connected?'btn-ghost':'btn-primary'}" onclick="toggleDrive()">${d.connected?'Off':'On'}</button></div><div class="connector-card"><div class="conn-icon ent">🏛️</div><div class="conn-body"><div class="conn-title">ENT / MyKomunoté</div><div class="conn-status"><span class="status-dot ${e.connected?'on':''}"></span>${e.connected?'Connecté':'Non connecté'}</div></div><button class="btn btn-sm ${e.connected?'btn-ghost':'btn-primary'}" onclick="toggleENT()">${e.connected?'Off':'On'}</button></div>`);}
function toggleDrive(){if(state.connectors.drive.connected){state.connectors.drive={connected:false,lastSync:null};}else{state.connectors.drive={connected:true,lastSync:'now'};}saveState();showToast(state.connectors.drive.connected?'Drive ON':'Drive OFF');openConnectors();}
function toggleENT(){if(state.connectors.ent.connected){state.connectors.ent={connected:false,lastSync:null,ifsiName:''};}else{state.connectors.ent={connected:true,ifsiName:state.profile.ifsi||'IFSI Demo',lastSync:'now'};}saveState();showToast(state.connectors.ent.connected?'ENT ON':'ENT OFF');openConnectors();renderAccueil();}
function openSettings(){const p=state.profile,s=state.settings;openScreen('Réglages',`<div class="profile-header"><div class="profile-avatar">${initials(p.prenom)}</div><div><h2>${esc(p.prenom||'Étudiant(e)')}</h2><p>${p.annee}e année · ${esc(p.ifsi||'IFSI')}</p></div></div><div class="card" style="padding:0 1rem"><div class="settings-row" onclick="editProfile()"><div class="row-left"><div class="row-icon">👤</div><div class="row-label">Profil</div></div><span>›</span></div><div class="settings-row"><div class="row-left"><div class="row-icon">💡</div><div class="row-label">Suggestions</div></div><button class="toggle ${s.suggestions?'on':''}" onclick="toggleSetting('suggestions')"></button></div><div class="settings-row" onclick="openConnectors()"><div class="row-left"><div class="row-icon">🔗</div><div class="row-label">Connecteurs</div></div><span>›</span></div><div class="settings-row" onclick="if(confirm('Reset?')){localStorage.removeItem(STORAGE_KEY);location.reload()}"><div class="row-left"><div class="row-icon">🗑️</div><div class="row-label" style="color:var(--danger)">Reset démo</div></div></div></div>`);}
function toggleSetting(k){state.settings[k]=!state.settings[k];saveState();openSettings();}
function editProfile(){openModal('Profil',`<div class="form-group"><label>Prénom</label><input id="edit-prenom" value="${esc(state.profile.prenom)}"></div><div class="form-group"><label>Année</label><select id="edit-annee"><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></div><div class="form-group"><label>IFSI</label><input id="edit-ifsi" value="${esc(state.profile.ifsi)}"></div><button class="btn btn-primary btn-block" onclick="saveProfile()">OK</button>`);}
function saveProfile(){state.profile.prenom=document.getElementById('edit-prenom').value.trim()||state.profile.prenom;state.profile.annee=document.getElementById('edit-annee').value;state.profile.ifsi=document.getElementById('edit-ifsi').value.trim();saveState();closeModal();openSettings();renderAccueil();}
function openSearch(){document.getElementById('search-overlay').classList.add('open');document.getElementById('global-search-input')?.focus();document.getElementById('search-results').innerHTML='<p class="text-sm text-muted" style="padding:1rem;text-align:center">Rechercher…</p>';}
function closeSearch(){document.getElementById('search-overlay')?.classList.remove('open');}
function runGlobalSearch(q){q=(q||'').toLowerCase().trim();const box=document.getElementById('search-results');if(!q){box.innerHTML='';return;}const results=[];state.soins.forEach(s=>{if(s.nom.toLowerCase().includes(q))results.push({icon:'💉',title:s.nom,go:()=>{closeSearch();switchTab('soins');renderSoins(s.nom);}});});state.tasks.forEach(t=>{if(t.text.toLowerCase().includes(q))results.push({icon:'✅',title:t.text,go:()=>{closeSearch();switchTab('accueil');}});});window._sr=results;box.innerHTML=results.slice(0,10).map((r,i)=>`<div class="search-result-item" onclick="window._sr[${i}].go()"><div class="sr-icon">${r.icon}</div><div class="sr-title">${esc(r.title)}</div></div>`).join('')||'<div class="empty-state"><p>Aucun résultat</p></div>';}
function openScreen(t,b){document.getElementById('screen-title').textContent=t;document.getElementById('screen-body').innerHTML=b;document.getElementById('screen-overlay').classList.add('open');}
function closeScreen(){document.getElementById('screen-overlay')?.classList.remove('open');if(currentTab==='accueil')renderAccueil();else if(currentTab==='terrain')renderTerrain();else if(currentTab==='fiches')renderFiches();else renderSoins();}
function openModal(t,b){document.getElementById('modal-title').textContent=t;document.getElementById('modal-body').innerHTML=b;document.getElementById('modal-overlay').classList.add('open');}
function closeModal(){document.getElementById('modal-overlay').classList.remove('open');}
const AI={default:'Assistant NEXSI (demo). Pose ta question !',app:'APP: Situation → Analyse → Apports → Axes.',stage:'Précise le service pour objectifs et checklist.',priorites:()=>state.priorities.map((x,i)=>(i+1)+'. '+x.title).join('\n')||'Aucune',pharmaco:'UE 2.11: classes, calcul dose (entraînement), surveillance.'};
function openAI(){document.getElementById('ai-panel').classList.add('open');if(!document.getElementById('ai-messages').children.length)addAIMessage('bot',AI.default);}
function closeAI(){document.getElementById('ai-panel')?.classList.remove('open');}
function addAIMessage(role,text){const m=document.getElementById('ai-messages');const d=document.createElement('div');d.className='ai-msg '+role;d.textContent=text;m.appendChild(d);m.scrollTop=m.scrollHeight;}
function sendAI(){const input=document.getElementById('ai-input');const text=input.value.trim();if(!text)return;addAIMessage('user',text);input.value='';setTimeout(()=>{let r=AI.default;const l=text.toLowerCase();if(l.includes('app'))r=AI.app;else if(l.includes('stage'))r=AI.stage;else if(l.includes('priorit'))r=AI.priorites();else if(l.includes('pharmaco'))r=AI.pharmaco;addAIMessage('bot',r);},400);}
function aiChip(key){const map={app:'Structurer mon APP',priorites:'Mes priorités ?',stage:'Préparer mon stage',pharmaco:'Pharmacologie'};document.getElementById('ai-input').value=map[key]||key;sendAI();}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;});
function installPWA(){if(!deferredInstallPrompt){showToast('Non disponible');return;}deferredInstallPrompt.prompt();}
function dismissInstall(){document.getElementById('install-banner')?.classList.remove('show');}
window.addEventListener('online',()=>document.getElementById('offline-bar')?.classList.remove('show'));
window.addEventListener('offline',()=>document.getElementById('offline-bar')?.classList.add('show'));
function init(){renderOnboarding();if(state.onboarded)renderAll();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});document.getElementById('ai-input')?.addEventListener('keydown',e=>{if(e.key==='Enter')sendAI();});document.getElementById('modal-overlay')?.addEventListener('click',e=>{if(e.target.id==='modal-overlay')closeModal();});}
document.addEventListener('DOMContentLoaded',init);
['switchTab','obNext','obSkip','toggleTask','setStatutGeste','handlePriority','openMockStage','openAddTask','saveNewTask','openAddTravail','saveNewTravail','openAddJournal','saveNewJournal','openModal','closeModal','openAI','closeAI','sendAI','aiChip','installPWA','dismissInstall','renderFiches','renderSoins','showToast','dismissTip','openConnectors','toggleDrive','toggleENT','openSettings','toggleSetting','editProfile','saveProfile','openSearch','closeSearch','runGlobalSearch','openScreen','closeScreen','openObjectifs','toggleObjectif','openChecklist','toggleChecklist','openJournalDetail','openCalculateur','runCalc'].forEach(n=>{try{window[n]=eval(n);}catch(e){}});
